version: "3"

services:
  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    environment:
      - DB_HOST=db
      - TOKEN_PASS=TopitoToken7.
      - DB_PASS=TopitoDb7.
      - DB_NAME=fastNoteDb
  db:
    image: postgres
    environment:
      POSTGRES_DB: fastNoteDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TopitoDb7.