version: "3"

services:
  api:
    image: oscaragudelo/fastnote-back
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - TOKEN_PASS=TopitoToken7.
      - DB_PASS=TopitoDb7.
      - DB_NAME=fastNoteDb
  db:
    image: postgres
    environment:
      POSTGRES_DB: fastNoteDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TopitoDb7.