name: back-dev

on:
  push:
    paths:
      - "back/**"
    branches:
      - "dev"

jobs:
  docker-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests back
        run: cd back/ && npm run docker-ci
      - name: Cancelling if test fails
        if: failure()
        uses: andymckay/cancel-action@0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:back"
          file: ./Dockerfile
          push: true
          tags: oscaragudelo/fastnote-back-dev
