name: back-tests-push

on:
  push:
    paths:
      - "back/**" 
    branches-ignore:    
      - "dev"
      - "main"

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests back
        run: cd back/ && npm run docker-ci
