name: back-test-PR

on:
  pull_request:
    paths:
      - "back/**"
    branches:
      - "dev"
      - "main"

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests back
        run: cd back/ && npm i && npm test
