name: front-tests-push

on:
  push:
    paths:
      - "front/**" 
    branches-ignore:    
      - "dev"
      - "main"

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests front
        run: cd front/ && npm i && npm test
